# This file contains all available configuration options
# with their default values.
# options for analysis running
run:
  issues-exit-code: 0
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m

# Output configuration options
output:
  format: line-number
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  sort-results: true

issues:

severity:
  default-severity: error
  case-sensitive: false

  rules:
  - linters:
    - exhaustivestruct
    - gomnd
    severity: info

linters:
  # enable-all: true

  disable:
  - gochecknoglobals # i know, but sometimes its required.
  - deadcode         # covered by `unused` and `varcheck`
  - testpackage      # opinionated
  - paralleltest     # covered by scopelint and tparalell

linters-settings:

  gocritic:
    enabled-tags: [  experimental, opinionated, performance, style ]

  forbidigo:
    forbid: [ "ginkgo\\.F.* " ]
    exclude_godoc_examples: true

  lll: { "line-length": 120, "tabwidth": 1 }

  maligned: {"suggest-new": true}

  nolintlint:
    allow-leading-space: false
    allow-unused: true
    require-explanation: false
    require-specific: false
